-- Sheet: Total Products
----------------------------------------------------------
SELECT
    COUNT(*) AS total_products
FROM products;

-- Sheet: Revenue Generated by Each Product
----------------------------------------------------------
SELECT
    product_id,
    ROUND(SUM(price), 2) AS revenue
FROM order_items
GROUP BY product_id
ORDER BY revenue DESC;

-- Sheet: Units Sold by Each Product
----------------------------------------------------------
SELECT
    product_id,
    COUNT(*) AS units_sold
FROM order_items
GROUP BY product_id
ORDER BY units_sold DESC;

-- Sheet: Top 10 Products by Revenue
----------------------------------------------------------
SELECT
    product_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY product_id
ORDER BY revenue DESC
LIMIT 10;

-- Sheet: Bottom 10 Products by Revenue
----------------------------------------------------------
SELECT
    product_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY product_id
ORDER BY revenue ASC
LIMIT 10;

-- Sheet: Rank Products by Revenue
----------------------------------------------------------
SELECT
    product_id,
    SUM(price) AS revenue,
    DENSE_RANK() OVER (ORDER BY SUM(price) DESC) AS product_rank
FROM order_items
GROUP BY product_id;

-- Sheet: Product Revenue Contribution %
----------------------------------------------------------
SELECT
    product_id,
    SUM(price) AS revenue,
    ROUND(
        SUM(price) * 100.0 / SUM(SUM(price)) OVER(),
        2
    ) AS contribution_percentage
FROM order_items
GROUP BY product_id
ORDER BY contribution_percentage DESC;

-- Sheet: Revenue by Product Category
----------------------------------------------------------
SELECT
    p.product_category_name,
    ROUND(SUM(price), 2) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY revenue DESC;

-- Sheet: Top 5 Products Within Each Category
----------------------------------------------------------
WITH product_sales AS
(
    SELECT
        p.product_category_name,
        p.product_id,
        SUM(price) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_category_name, p.product_id
)
SELECT *
FROM
(
    SELECT *,
        DENSE_RANK() OVER(PARTITION BY product_category_name ORDER BY revenue DESC) AS rnk
    FROM product_sales
) t
WHERE rnk <= 5;

-- Sheet: Bottom 5 Products Within Each Category
----------------------------------------------------------
WITH product_sales AS
(
    SELECT
        p.product_category_name,
        p.product_id,
        SUM(price) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_category_name, p.product_id
)
SELECT *
FROM
(
    SELECT *,
        DENSE_RANK() OVER(PARTITION BY product_category_name ORDER BY revenue ASC) AS rnk
    FROM product_sales
) t
WHERE rnk <= 5;

-- Sheet: Monthly Product Revenue
----------------------------------------------------------
SELECT
    oi.product_id,
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    SUM(price) AS revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY oi.product_id, month
ORDER BY oi.product_id, month;

-- Sheet: Running Revenue Per Product
----------------------------------------------------------
WITH monthly_product AS
(
    SELECT
        oi.product_id,
        DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
        SUM(price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY oi.product_id, month
)
SELECT
    *,
    SUM(revenue) OVER(PARTITION BY product_id ORDER BY month) AS running_revenue
FROM monthly_product;

-- Sheet: Previous Month Revenue Per Product
----------------------------------------------------------
WITH monthly_product AS
(
    SELECT
        oi.product_id,
        DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
        SUM(price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY oi.product_id, month
)
SELECT
    *,
    LAG(revenue) OVER(PARTITION BY product_id ORDER BY month) AS previous_month_revenue
FROM monthly_product;

-- Sheet: Revenue Difference
----------------------------------------------------------
WITH monthly_product AS
(
    SELECT
        oi.product_id,
        DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
        SUM(price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY oi.product_id, month
)
SELECT
    *,
    revenue - LAG(revenue) OVER(PARTITION BY product_id ORDER BY month) AS revenue_difference
FROM monthly_product;

-- Sheet: Product Moving Average
----------------------------------------------------------
WITH monthly_product AS
(
    SELECT
        oi.product_id,
        DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
        SUM(price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY oi.product_id, month
)
SELECT
    *,
    AVG(revenue) OVER(PARTITION BY product_id ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_average
FROM monthly_product;

-- Sheet: Average Product Price by Category
----------------------------------------------------------
SELECT
    p.product_category_name,
    ROUND(AVG(oi.price), 2) AS average_price
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY average_price DESC;

-- Sheet: Most Expensive Products Sold
----------------------------------------------------------
SELECT
    product_id,
    MAX(price) AS highest_price
FROM order_items
GROUP BY product_id
ORDER BY highest_price DESC
LIMIT 10;

-- Sheet: Product Sales Percentage by Category
----------------------------------------------------------
SELECT
    p.product_category_name,
    COUNT(*) AS units_sold,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(),
        2
    ) AS sales_percentage
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY sales_percentage DESC;

-- Sheet: Product Performance Dashboard
----------------------------------------------------------
SELECT
    oi.product_id,
    SUM(price) AS revenue,
    COUNT(*) AS units_sold,
    ROUND(AVG(price), 2) AS average_price,
    ROUND(AVG(freight_value), 2) AS average_freight
FROM order_items oi
GROUP BY oi.product_id
ORDER BY revenue DESC;

-- Sheet: Pareto Analysis (Top Revenue Products)
----------------------------------------------------------
WITH product_sales AS
(
    SELECT
        product_id,
        SUM(price) AS revenue
    FROM order_items
    GROUP BY product_id
)
SELECT
    product_id,
    revenue,
    SUM(revenue) OVER (ORDER BY revenue DESC) AS running_revenue,
    ROUND(
        SUM(revenue) OVER (ORDER BY revenue DESC) * 100.0 / SUM(revenue) OVER(),
        2
    ) AS cumulative_percentage
FROM product_sales
ORDER BY revenue DESC;