/*=========================================================================
                    SELLER PERFORMANCE ANALYSIS
                  OLIST BRAZIL E-COMMERCE
=========================================================================*/


----------------------------------------------------------
-- Sheet: Total Sellers
----------------------------------------------------------

SELECT
    COUNT(*) AS total_sellers
FROM sellers;



----------------------------------------------------------
-- Sheet: Revenue Generated by Each Seller
----------------------------------------------------------

SELECT
    seller_id,
    ROUND(SUM(price),2) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;



----------------------------------------------------------
-- Sheet: Number of Orders Handled by Each Seller
----------------------------------------------------------

SELECT
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_items
GROUP BY seller_id
ORDER BY total_orders DESC;



----------------------------------------------------------
-- Sheet: Average Order Value Per Seller
----------------------------------------------------------

SELECT
    seller_id,
    ROUND(
        SUM(price) /
        COUNT(DISTINCT order_id),
        2
    ) AS avg_order_value
FROM order_items
GROUP BY seller_id
ORDER BY avg_order_value DESC;



----------------------------------------------------------
-- Sheet: Top 10 Sellers by Revenue
----------------------------------------------------------

SELECT
    seller_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC
LIMIT 10;



----------------------------------------------------------
-- Sheet: Bottom 10 Sellers by Revenue
----------------------------------------------------------

SELECT
    seller_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue
LIMIT 10;



----------------------------------------------------------
-- Sheet: Rank Sellers by Revenue
----------------------------------------------------------

SELECT
    seller_id,
    SUM(price) AS revenue,
    DENSE_RANK() OVER(
        ORDER BY SUM(price) DESC
    ) AS seller_rank
FROM order_items
GROUP BY seller_id;



----------------------------------------------------------
-- Sheet: Percent Rank of Sellers
----------------------------------------------------------

SELECT
    seller_id,
    revenue,
    PERCENT_RANK() OVER(
        ORDER BY revenue
    ) AS percent_rank
FROM
(
SELECT
    seller_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY seller_id
)t;



----------------------------------------------------------
-- Sheet: Revenue Contribution of Each Seller
----------------------------------------------------------

SELECT
    seller_id,
    SUM(price) AS revenue,

    ROUND(
        SUM(price)*100/
        SUM(SUM(price)) OVER(),
        2
    ) AS contribution_percentage

FROM order_items
GROUP BY seller_id
ORDER BY contribution_percentage DESC;



----------------------------------------------------------
-- Sheet: Monthly Revenue Per Seller
----------------------------------------------------------

SELECT
    oi.seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) AS month,
    SUM(price) AS revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
ORDER BY seller_id,month;



----------------------------------------------------------
-- Sheet: Previous Month Revenue Per Seller
----------------------------------------------------------

WITH seller_monthly AS
(
SELECT
    oi.seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) AS month,
    SUM(price) AS revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
)

SELECT
    *,
    LAG(revenue)
    OVER(
        PARTITION BY seller_id
        ORDER BY month
    ) previous_month_revenue
FROM seller_monthly;



----------------------------------------------------------
-- Sheet: Monthly Revenue Difference
----------------------------------------------------------

WITH seller_monthly AS
(
SELECT
    oi.seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) AS month,
    SUM(price) revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
)

SELECT
    *,
    revenue-
    LAG(revenue)
    OVER(
        PARTITION BY seller_id
        ORDER BY month
    ) revenue_difference
FROM seller_monthly;



----------------------------------------------------------
-- Sheet: Running Revenue Per Seller
----------------------------------------------------------

WITH seller_monthly AS
(
SELECT
    oi.seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) month,
    SUM(price) revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
)

SELECT
    *,
    SUM(revenue)
    OVER(
        PARTITION BY seller_id
        ORDER BY month
    ) cumulative_revenue
FROM seller_monthly;



----------------------------------------------------------
-- Sheet: Seller Revenue Growth %
----------------------------------------------------------

WITH seller_monthly AS
(
SELECT
    oi.seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) month,
    SUM(price) revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
)

SELECT
    *,
    ROUND(
        (
            revenue -
            LAG(revenue)
            OVER(
                PARTITION BY seller_id
                ORDER BY month
            )
        )
        /
        LAG(revenue)
        OVER(
            PARTITION BY seller_id
            ORDER BY month
        )
        *100,
        2
    ) growth_percentage
FROM seller_monthly;



----------------------------------------------------------
-- Sheet: Top 5 Sellers Each Month
----------------------------------------------------------

WITH seller_monthly AS
(
SELECT
    seller_id,
    DATE_TRUNC('month',o.order_purchase_timestamp) month,
    SUM(price) revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY seller_id,month
)

SELECT *
FROM
(
SELECT
    *,
    DENSE_RANK()
    OVER(
        PARTITION BY month
        ORDER BY revenue DESC
    ) rnk
FROM seller_monthly
)t
WHERE rnk<=5;



----------------------------------------------------------
-- Sheet: Sellers by Number of Products Sold
----------------------------------------------------------

SELECT
    seller_id,
    COUNT(product_id) AS products_sold
FROM order_items
GROUP BY seller_id
ORDER BY products_sold DESC;



----------------------------------------------------------
-- Sheet: Sellers with Highest Freight Charges
----------------------------------------------------------

SELECT
    seller_id,
    ROUND(SUM(freight_value),2) AS freight_cost
FROM order_items
GROUP BY seller_id
ORDER BY freight_cost DESC;



----------------------------------------------------------
-- Sheet: Average Review Score Per Seller
----------------------------------------------------------

SELECT
    oi.seller_id,
    ROUND(AVG(orv.review_score),2) AS average_review
FROM order_items oi
JOIN order_reviews orv
ON oi.order_id=orv.order_id
GROUP BY oi.seller_id
ORDER BY average_review DESC;



----------------------------------------------------------
-- Sheet: Average Delivery Time Per Seller
----------------------------------------------------------

SELECT
    oi.seller_id,

    ROUND(
        AVG(
            o.order_delivered_customer_date -
            o.order_purchase_timestamp
        ),
        2
    ) AS avg_delivery_days

FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id

WHERE o.order_delivered_customer_date IS NOT NULL

GROUP BY oi.seller_id
ORDER BY avg_delivery_days;



----------------------------------------------------------
-- Sheet: Seller Performance Dashboard
----------------------------------------------------------

SELECT
    oi.seller_id,

    COUNT(DISTINCT oi.order_id) AS total_orders,

    SUM(price) AS revenue,

    ROUND(AVG(price),2) AS average_item_price,

    ROUND(AVG(freight_value),2) AS average_freight,

    ROUND(AVG(orv.review_score),2) AS average_review

FROM order_items oi

JOIN order_reviews orv
ON oi.order_id=orv.order_id

GROUP BY oi.seller_id

ORDER BY revenue DESC;